name: CI
run-name: ${{ github.actor }} one
on:
  push:
  pull_request:

jobs:
  testInitialSetup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Debug frontend
        run: |
          pwd
          ls -la
          ls -la frontend
          ls -la frontend/package-lock.json

      - name: Install modules
        run: cd frontend && npm ci

      - name: Lint code
        run: cd frontend && npm run lint

      - name: Unit tests
        run: cd frontend && npm run test:unit

      - name: Build project
        run: cd frontend && npm run build

      - name: Build storybook
        run: cd frontend && npm run build-storybook

      - name: E2E tests
        run: cd frontend && npm run test:e2e